site_name: zhus Docs

#repo_name: 'Github Star'
repo_url: 'https://github.com/zhus2015/docs'
edit_uri: ''

theme:
    name: 'material'
    #name: 'Bootstrap'
    logo: 'images/facio.ico'
    favicon: 'images/facio.ico'
    language: 'zh'
    highlightjs: true
    feature:
        tabs: true
    hljs_languages:
        - yaml
        - django
    font:
        text: Roboto
        code: Roboto Mono
    palette:
        scheme: default
        primary: black
        accent: indigo
        
plugins:
    - search
#copyright: 
#google_analytics:

nav:
    - 介绍: index.md
    - 系统运维基础:
        - Linux基础:
            - Centos 7 关闭桌面: system_base/linux/centos7_stop_desktop.md
            - 更换软件安装源: system_base/linux/change_soft_source.md
            - 定时任务使用配置: system_base/linux/linux_crontab.md
            - 系统网络配置: system_base/linux/linux_network_setting.md
            - sytemctl进程管理: system_base/linux/centos7_systemctl_setting.md
        - Shell: 
            - Shell基础: system_base/shell/shell.md
            - Shell小实验: system_base/shell/shell_test.md
            - expect交互脚本: system_base/shell/expect.md
            - 正则匹配: system_base/shell/regular_expression.md
        - 常用服务:
            - FTP: 
                - FTP安装部署: system_base/common_services/ftp_install.md
                - FTP错误代码: system_base/common_services/ftp_error_code.md
                - FTP相关脚本: system_base/common_services/ftp_scripte.md
            - DNS:
                - Bind9安装配置: system_base/common_services/bind9.md
            - Rsync:
                - Sersync配置文件同步: system_base/common_services/sersync.md
        - 中间件: 
            - Nginx:
                - Nginx的内置变量: system_base/middleware/nginx/nginx_var.md
                - Nginx处理跨域问题: system_base/middleware/nginx/nginx_cross_domain.md
                - Nginx常用配置: system_base/middleware/nginx/nginx_config.md
    - 高可用:
        - LVS简介: HA/lvs.md
        - Keepalived高可用: HA/keepalived.md
        - Haproxy: HA/haproxy.md
            

    - 数据库:
        - Oracle:
            - Centos7下静默安装Oracle: database/oracle/oracle_install.md
            - Oracle日常操作: database/oracle/oracle_use.md
        - Mysql:
            - Mysql安装部署: database/mysql/mysql_install.md
        - Redis:
            - Redis安装部署: database/redis/redis_install.md
        - Mongodb:
            - Mongodb安装部署: database/mongodb/mongodb_install.md
            - Mongodb日常使用: database/mongodb/mongodb_use.md
 
    - 代码文档管理: 
        - 代码管理:
            - SVN: code_docs/code_manage/svn.md
            - Gogs: code_docs/code_manage/gogs.md
            - Gitlab: code_docs/code_manage/gitlab.md
        - 代码质量管理:
            - sonarqube: code_docs/code_quality/sonarqube.md
        - 文档管理:
            - confluence: code_docs/docs_manage/confluence.md
            
    - 开源监控: 
        - Zabbix:
            - Zabbix安装部署: open_source_monitor/zabbix/zabbix_install.md
        - Promethues:
            - Prometheus安装部署: open_source_monitor/prometheus/prometheus_install.md
        - Grafana: 
            - Grafana简介: open_source_monitor/grafana/grafana_about.md
            - Grafana安装: open_source_monitor/grafana/grafana_install.md           
 
    - Devops:
        - 配置管理工具:
            - Ansiable: devops/config_manage_tools/ansible.md
            - Puppet: devops/config_manage_tools/puppet.md
            - SaltStack: devops/config_manage_tools/saltstack.md
                        
        - Jenkins:
            - Jenkins 安装部署: devops/jenkins/jenkins_install.md
            - Jenkins 参数化构建: devops/jenkins/jenkins_build_arge.md
            - Jenkins Maven打包程序: devops/jenkins/jenkins_build_java.md
            - Jenkins SSH通道部署程序: devops/jenkins/jenkins_deploy_ssh.md
            - Jenkins Webhook触发构建: devops/jenkins/jenkins_webhook_build.md
            - Jenkins Pipeline语法说明: devops/jenkins/jenkins_pipeline.md
            - Jeknins 配置钉钉通知: devops/jenkins/jenkins_message_dingding.md
            - Jenkins 打包APK: devops/jenkins/jenkins_build_apk.md
            
        - ELK: 
            - ELK安装部署: devops/elk/elk_install.md
            - ELK收集Nginx日志: devops/elk/elk_collect_nginx_logs.md
            
    - Docker:
        - Docker基础: devops/docker/docker_basic.md
        - Docker的网络模式: devops/docker/docker_network.md
        - Docker镜像仓库--Harbor: devops/docker/docker_library_harbor.md
        - 制作jre镜像: devops/docker/make_jre_images.md
        - 制作运行jar包的镜像: devops/docker/make_jre_jar_images.md
        - 制作tomcat镜像: devops/docker/make_tomcat_images.md
        
    - Kubernetes:
        - K8S基础知识: 
            - 简介: Kubernetes/base/k8s_base_knowledge.md
            - 三种IP: Kubernetes/base/k8s_base_ip.md
            - Pod调度: Kubernetes/base/k8s_pod_schedule.md
            
        - K8S安装部署:  
            - K8S安装部署(基础组件): Kubernetes/deploy/k8s_base_install_new.md
            - K8S安装部署(核心插件): Kubernetes/deploy/k8s_core_plug_install.md
            - K8S交付apollo配置中心: Kubernetes/deploy/k8s_apollo_install.md
            - K8S交付Dubbo微服务: Kubernetes/deploy/k8s_dubbo_install_new.md
            - K8S交付Dubbo-monitor微服务: Kubernetes/deploy/k8s_dubbo_monitor_install.md
            - K8S交付Prometheus监控(1): Kubernetes/deploy/k8s_prometheus_install_1.md
            - K8S交付Prometheus监控(2): Kubernetes/deploy/k8s_prometheus_install_2.md
            - K8S使用ELK收集日志: Kubernetes/deploy/k8s_elk_install.md
            - Kubeadmin安装k8s集群: Kubernetes/deploy/k8s_kubeadm_install.md
        
        - K8s进阶:
            - K8S包管理工具-Helm: Kubernetes/advanced/k8s_helm.md
            - K8S证书更新: Kubernetes/advanced/k8s_kubeadm_ca_update.md
        
        - CKA资料:
            - Kubernetes/cka/CKA真题分享.md
            - Kubernetes/cka/2019考试真题.md
            - Kubernetes/cka/20190714考试真题.md
            
    - 开发学习:
        - Python:
            - Python基础: 
                - 基础语法: Development/python/python_base/python_basic_grammar.md
                - 数据类型: Development/python/python_base/python_data_type.md
                - 列表操作: Development/python/python_base/python_list.md
                - 文件操作: Development/python/python_base/python_file.md
                - 字符操作: Development/python/python_base/python_string.md
     
    - 开源软件: open_source/open_source.md
    
    - 关于:
         - 联系方式: about/contact.md
         - MKdocs使用: about/mkdocs.md
         - 图: about/test.md
         
markdown_extensions:
    - markdown.extensions.attr_list
    - admonition
    - codehilite:
        guess_lang: True
        linenums: False
    - toc:
        permalink: True
    - footnotes
    - attr_list
    - def_list
    - tables
    - abbr
    - md_in_html
    - pymdownx.extra
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.progressbar

extra_css:
    - css/extra.css
    - css/simpleLightbox.min.css
    - css/custom.css
    
extra_javascript:
    - 'js/extra.js'
    - 'js/simpleLightbox.js'
    - 'js/custom.js'
    - js/umlconvert.js
