site_name: zhus Docs

#repo_name: 'Github Star'
repo_url: 'https://github.com/zhus2015/docs'
edit_uri: ''

theme:
    name: 'material'
    #name: 'cosmo'
    #logo: 'img/logo.png'
    favicon: 'images/facio.ico'
    language: 'zh'
    highlightjs: true
    feature:
        tabs: true
    hljs_languages:
        - yaml
        - bash
    #font: false
    palette:
        primary: 'indigo'
        accent: 'indigo'
  
nav:
    - 介绍: index.md
    - 系统基础:
        - Linux基础:
            - Centos 7 关闭桌面: system_base/linux/centos7_stop_desktop.md
            - 更换软件安装源: system_base/linux/change_soft_source.md
        - Shell: 
            - Shell基础: system_base/shell/shell.md
            - Shell逻辑判断: system_base/shell/shell_logic.md
            - Shell小实验: system_base/shell/shell_test.md
            - expect交互脚本: system_base/shell/expect.md
            
    - 常用服务:
        - FTP: 
            - FTP错误代码: common_services/vsftp_error_code.md
            - FTP安装脚本: common_services/vsftp_install_scripte.md
        - DNS:
            - Bind9安装配置: common_services/bind9.md
        - Rsync:
            - Sersync配置文件同步: common_services/sersync.md
            
    - 高可用:
        - Keepalived高可用: HA/keepalived.md
            
    - 中间件: 
        - Nginx:
            - Nginx的内置变量: middleware/nginx/nginx_var.md
            - Nginx处理跨域问题: middleware/nginx/nginx_cross_domain.md
    - 数据库:
        - Oracle:
            - Linux下静默安装部署: database/oracle/oracle_install.md
            
    - 代码文档管理: 
        - 代码管理:
            - gogs: code_docs/code_manage/gogs.md
            - gitlab: code_docs/code_manage/gitlab.md
        - 代码质量管理:
            - sonarqube: code_docs/code_quality/sonarqube.md
        - 文档管理:
            - confluence: code_docs/docs_manage/confluence.md
            
    - 开源监控: 
        - Zabbix:
            - Zabbix安装部署: open_source_monitor/zabbix/zabbix_install.md
        - Promethues:
            - Prometheus安装部署: open_source_monitor/prometheus/prometheus_install.md
        - Grafana: 
            - Grafana简介: open_source_monitor/grafana/grafana_about.md
            - Grafana安装: open_source_monitor/grafana/grafana_install.md
            
    - 日志收集处理:
        - ELK: 
            - ELK安装部署: logs/elk/elk_install.md
            
    - CI/CD:
        - Jenkins:
            - Jenkins安装部署: devops/jenkins/jenkins_install.md
            - Jenkins通过maven打包程序: devops/jenkins/jenkins_build_java.md
            - Jenkins参数化构建: devops/jenkins/jenkins_build_arge.md
            - Jenkins通过ssh通道部署: devops/jenkins/jenkins_deploy_ssh.md
            - Jenkins Pipeline语法说明: devops/jenkins/jenkins_pipeline.md
            - Jeknins项目构建钉钉通知配置: devops/jenkins/jenkins_message_dingding.md
    - 容器云:
        - Docker:
            - Docker基础: container_cloud/docker/docker_basic.md
            - Docker的网络模式: container_cloud/docker/docker_network.md
            - Docker镜像仓库--Harbor: container_cloud/docker/docker_library_harbor.md
            - 制作jre镜像: container_cloud/docker/make_jre_images.md
            - 制作运行jar包的镜像: container_cloud/docker/make_jre_jar_images.md
            - 制作tomcat镜像: container_cloud/docker/make_tomcat_images.md          
        - K8S: 
            - K8S基础知识: container_cloud/k8s/k8s_base_knowledge.md
            - K8S安装基础组件: container_cloud/k8s/k8s_base_install.md
            - K8S安装核心组件: container_cloud/k8s/k8s_core_install.md
            - K8S交付apollo配置中心: container_cloud/k8s/k8s_apollo_install.md
            - K8S交付Dubbo微服务: container_cloud/k8s/k8s_dubbo_install.md
            - K8S交付Dubbo-monitor微服务: container_cloud/k8s/k8s_dubbo_monitor_install.md
            - kubeadmin安装k8s集群: container_cloud/k8s/k8s_kubeadm_install.md
    - Python:
        - Python基础: python/python_base/python_list.md
    - 资源文件: file/sersync2.5.4_64bit_binary_stable_final.tar.gz
        
    - 关于:
         - 联系方式: about/contact.md
         - MKdocs使用: about/mkdocs.md

markdown_extensions:
    - markdown.extensions.attr_list
    - admonition
    - codehilite:
        guess_lang: True
        linenums: False
    - toc:
        permalink: True
    - footnotes
    - attr_list
    - def_list
    - tables
    - abbr
    - md_in_html
    - pymdownx.extra
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.superfences
    - pymdownx.progressbar

extra_css:
    - css/extra.css
    - css/simpleLightbox.min.css
    - css/custom.css
    
extra_javascript:
    - 'js/extra.js'
    - 'js/simpleLightbox.js'
    - 'js/custom.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    - 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js'


#copyright: 
#google_analytics:
plugins:
    - search