site_name: zhus Docs

theme:
    name: 'material'
    #logo: 'img/logo.png'
    #favicon: 'img/facio.ico'
    language: 'zh'
    highlightjs: true
    feature:
        tabs: true
    hljs_languages:
        - yaml
        - django

    palette:
        primary: 'green'
        accent: 'red'
  
nav:
    - 介绍: index.md
    - K8S:
      - 安装文档: k8s/k8s_base_install.md

     
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: True
        linenums: False
    - toc:
        permalink: True
    - footnotes
    - attr_list
    - def_list
    - tables
    - abbr
    - md_in_html
    - pymdownx.extra
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.superfences
    - pymdownx.progressbar